version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  #backend:
    # Uncomment and modify the backend service if you have a Dockerfile for it, or remove if not needed
    # build:
    #   context: ./backend
    # ports:
    #   - "5000:5000"
